### ISSUE TITLE
Warnings with react native upgrade

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [aksonov/react-native-router-flux#1000]
### Version

Tell us which versions you are using: 
- react-native-router-flux ^3.30.2
- react-native ^0.28.0
- react 15.3.0
### Expected behaviour

No warnings
### Actual behaviour

`ExceptionsManager.js:70 Warning: You are manually calling a React.PropTypes validation function for the`height`prop on`StyleSheet tabbarView`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`

I get this warning for most files (scene, tabbar etc)

**Comment by jschoolcraft** [comment]
I have a bunch of similar warnings:

## Versions

- "react": "^15.2.0",
- "react-native": "^
- "react-native-router-flux": "^3.32.0",

ExceptionsManager.js:76Warning: You are manually calling a React.PropTypes validation function for the `left` prop on `StyleSheet leftButton`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

ExceptionsManager.js:76Warning: You are manually calling a React.PropTypes validation function for the `fontSize` prop on `StyleSheet barRightButtonText`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by ziv-moonsite** [comment]
Same problem here.

**Comment by amos80m** [comment]
same issue
"react": "^15.2.1"
"react-native": "^0.31.0"
"react-native-router-flux": "^3.34.0"

**Comment by tuneZola** [comment]
Same problem
