### ISSUE TITLE
Experimental Native Navigation (iOS)

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#1061]
Hi all,
Unfortunately JS navigation could be laggy and doesn't look the same as iOS native one. So I've decided to implement RNRN : https://github.com/aksonov/react-native-router-native (RNRF-like wrapper with similar syntax, but not fully compatible, of course)

Maybe it could be interested for some. It is NOT based on ExperimentalNavigation API, but just wrapper around forked react-native-controllers: https://github.com/aksonov/react-native-controllers. Disadvantage that you can't customise native NavBar much (just icon/colors/fonts/onPress handlers for left/right buttons), but it is Native one!

Also I've proposed to authors of react-native-controllers to unite efforts and add Native Android support to it:
https://github.com/wix/react-native-controllers/issues/87#issuecomment-239818023

Feedback is welcome!

**Comment by digitaldavenyc** [comment]
Not being able to customize the NavBar would be a huge issue for our app. Our primary view has a search area that is designed in a way that's not possible without a custom NavBar.

**Comment by vonovak** [comment]
I'm also not a fan of the current JS-based navigation, however, I'd first like to see this library use the NavigationExperimental from RN core (I believe it will become stable in a couple of weeks) and have something that is fully usable. Maybe it's already implemented but last time I checked I was missing platform-specific animations for scene transitions.
Some other thoughts - consider
```
<Scene
       ....
       onRight={() => alert('Right button')}
       rightTitle="Right"
/>
```
I'm building an app for both iOS and android with completely different navbars for the two platforms and I feel like the code that has something to do with a navbar (onRight, rightTitle) should be moved to the respective components instead of being part of the `Scene`. Thanks for the lib!
