### ISSUE TITLE
BackAndroid pops two scenes when navigating back from a subscene

### ISSUE THREAD

**Issue by vonovak** [aksonov/react-native-router-flux#1084]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.31.0
### Description

When using subscenes - consider that you navigate like this: root -> list of emails -> edit the list (which is a `subscene` where you can select emails and e.g. archive them like in the gmail app) and while the editing is active, you press the back button. Instead of rendering the list of emails, RNRF renders the root scene. It appears the subscene is not added to the nav stack. 
### Expected Behavior

I believe the correct behavior would be to pop to the list of emails.

**Comment by Brokray** [comment]
I had the same "issue" using RNRF 3.35 & RN 0.30, and didn't understood it because it was working fine some days ago. 

But, in fact, the "problem" is that now _(15 days ago)_ `BackAndroid` is already supported by RNRF, you just have to set it up when you declare your Router. [See the code for the properties name.](https://github.com/aksonov/react-native-router-flux/blob/0ef1f7a19ca30d99e1892595da5be67a15c8fc22/src/Router.js#L58-L82)

**Comment by Swordsman-Inaction** [comment]
Check this for help #1049 . And here is the [document](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#router)

**Comment by Swordsman-Inaction** [comment]
And check [this](https://github.com/aksonov/react-native-router-flux/issues/1165#issuecomment-248264519)
