### ISSUE TITLE
Parent Containers don't work

### ISSUE THREAD

**Issue by nesbtesh** [aksonov/react-native-router-flux#1121]
### Version

v3
### Expected behavior

Allow you to create parent containers that pass down the props. 
See: https://medium.com/@nesbtesh/react-best-practices-a76fd0fbef21#.qwrlef6uk
### Actual behavior

The current functionality doesn't allow you to create containers which makes things really hard to work with.

**Comment by ThaJay** [comment]
Are you talking about getting a fatal error when using `this.props.children`?
If so I have encountered the same problem. Haven't tied it to rnrf but also haven't been able to repro it on the react-native sample project.

Why do you think this is related to rnrf? I would really like to be able to make wrapper components again because this is hurting my code structure at the moment.
