### ISSUE TITLE
How to move to the bottom navbar?

### ISSUE THREAD

**Issue by gHashTag** [aksonov/react-native-router-flux#1218]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.34.0

### Expected behaviour
I wish to place at the bottom Navbar

### Actual behaviour
He's at the top.

### Steps to reproduce
`<Router>
        <Scene key='root' navigationBarStyle={{backgroundColor: 'gold',  marginBottom: 1}}>
          <Scene key='pageOne' direction='vertical' duration={400} component={PageOne} title='PageOne' initial={true} />
      </Router>
`

**Comment by GantMan** [comment]
I think this is what you want:
https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#tabbar

**Comment by compojoom** [comment]
pass the following navigation style:
```
navigationBarStyle={{backgroundColor: 'red', bottom: 0, top: null}}
```

The navbar is absolutely positioned at the top. The style is defined in the NavBar.js of router-flux. in the header class the top property is set to 0 and that's why you have the navigation set to the top. Adding a bottom of 0 and resetting top by setting it to null, renders the navigation bar at the bottom.

**Comment by charpeni** [comment]
I'll close this issue since it's seem answered, if not please reopen it and let me know.

**Comment by infacq** [comment]
@compojoom i get extra height. How do I get it rid

**Comment by SSTPIERRE2** [comment]
Now in V4 it seems that styling the nav bar away from its original position results in a black, empty space where it originally was. See screenshot here: https://www.dropbox.com/s/zxccng7az8szo4e/Screenshot%202017-12-01%2009.12.45.png?dl=0
