### ISSUE TITLE
Displaying Image in Header (NavBar)

### ISSUE THREAD

**Issue by Abbondanzo** [aksonov/react-native-router-flux#1255]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.34.0
### Expected behaviour
- Image supposed to act as background for header
### Actual behaviour
- No image appears in the navigation bar and the header takes on an off-white color tone
### Steps to reproduce

```
<Scene key="root" navigationBarBackgroundImage={require('../img/header.png')} navigationBarStyle={{backgroundColor: '#222'}}> (It's set to #222 as a fallback, but removing the color does not display the image) 
     ...
</Scene>
```
1. Create router w/ menu
2. Add image to navigationBarBackgroundImage
3. Write issue report stating that images aren't taken

![](https://s13.postimg.org/6gam3igyf/d20ad8cd210578444ad1b19899c299c4.png)

**Comment by jaronoff97** [comment]
I'd also like to know the answer to this please!

**Comment by BunHouth** [comment]
That's what i looking for too.

**Comment by hilkeheremans** [comment]
After some fiddling and looking around (see #1082), it seems you can use the following:
```
        navigationBarBackgroundImage={{
            uri: 'navbar-background',
            width: Dimensions.get('window').width,
            height: 64,
        }}
```
Unfortunately, I could not get this to work with an image that is `require`'d, only with images that are included manually in (for example) Xcode as a resource. If anyone figures this out, let me know, since I don't have time to research this further.

Also, don't forget to set the navigation bar background to transparent, or the image might get hidden behind the navbar.

**Comment by hilkeheremans** [comment]
Oh, one more thing: make sure you are using at least `v3.36.0`!

**Comment by hilkeheremans** [comment]
Since not investigating this further came back to bite me in the butt, I submitted #1259 which should help you set the nav bar in the future. Using this version (`npm i https://github.com/tsjing/react-native-router-flux`) you should be able to set `navigationBarBackgroundImage={require('../img/header.png')}`, after which the image will get auto stretched across the entire nav bar.

Feel free to chime in/add on the PR if you have an additional need for features, but this works fine for me.

**Comment by infacq** [comment]
I think this has been solve before. See https://github.com/aksonov/react-native-router-flux/issues/1301

**Comment by Takeno** [comment]
@hilkeheremans following your suggestion, here my solution for local images:

```javascript
import resolveAssetSource from 'resolveAssetSource';

const HEADER_PATTERN = resolveAssetSource(require('../assets/header-pattern.png'));
[...]
    navigationBarBackgroundImage: {
        uri: HEADER_PATTERN.uri, // resolved uri
        scale: HEADER_PATTERN.scale, // resolved scale
        width: DEVICE_WIDTH, // custom dimensions
        height: 70,
    },
[...]
```

Probably, the right way is having another props for `navigationBarBackgroundImageStyle`.

**Comment by filipemonteiroth** [comment]
Check this pull request https://github.com/aksonov/react-native-router-flux/pull/1634

**Comment by filipemonteiroth** [comment]
The pull request with background image style is now on master.

https://github.com/aksonov/react-native-router-flux/pull/1663

**Comment by Devikaelangovan** [comment]
In my case, image is not stretching across the navbar. How to resolve this issue?

i set 
navigationBarBackgroundImage={require('../image.png')}
