### ISSUE TITLE
Unexpected back button target

### ISSUE THREAD

**Issue by johnwiseheart** [aksonov/react-native-router-flux#1286]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.35.0

### Expected behaviour

Pressing back button would go to the previous page it was on.

### Actual behaviour

Pressing back button goes to the first page on the current tab selected

### Steps to reproduce

With this scene structure:
```
<Scene key="main" tabs={true}>
    <Scene key="search" component={Search} title="Search" />
    <Scene key="projects_wrapper" title="My Projects">
         <Scene key="artefact" component={Artefact}/>
         <Scene key="collection" component={ProjectCollection}/>
         <Scene key="project" component={Project}/>
         <Scene key="projects" component={Projects} title="My Projects" initial />
    </Scene>
</Scene>
```
1. Be on the "search" tab and navigate to the "project" tab using Actions.project()
2. Click back button in the top left
3. Find yourself on the "projects" scene, instead of back at the search scene.

I've been trying to figure this out for a while with no success - can anyone offer some advice?

Cheers

**Comment by ryanoboril** [comment]
It seems like stack navigation (push transitions) only work within tab container scenes;  if you call a scene from another tab "stack", it switches navigation context to that stack, upon which nothing has yet been pushed, so the back button goes back to the initial scene of that tab container scene (in your case, Projects).  However, it is still possible to reuse scene components if you copy them into different scenes that have unique key names, and you parameterize any scene transitions within the reused scene component as props (not shown here as it does not apply to this example).

For your example use case, try the following and see if you get your expected behavior:

<Scene key="main" tabs={true}>
    <Scene key="search_wrapper" title="Search">
         <Scene key="search" component={Search}/>
         <Scene key="project" component={Project}/>
    </Scene>
    <Scene key="projects_wrapper" title="My Projects">
         <Scene key="artefact" component={Artefact}/>
         <Scene key="collection" component={ProjectCollection}/>
         <Scene key="project2" component={Project}/>
         <Scene key="projects" component={Projects} title="My Projects" initial />
    </Scene>
</Scene>

(NOTE: the original Project scene key was renamed to "project2" because the keys need to be unique, and I wanted to provide an example that satisfied the presented use case; in practice, you might want to call the project scene in the search_wrapper "searchProject" or similar).

**Comment by johnwiseheart** [comment]
This seems like a pretty good solution. The solution I came to was providing the onBack attribute on each navigation call, which wasn't that nice of a way to handle it.
