### ISSUE TITLE
Question: Is there a way to disable the sliding animation of the title?

### ISSUE THREAD

**Issue by stonepreston** [aksonov/react-native-router-flux#1537]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37
- react-native v0.40

Is there any way to disable the title animation? Ive got some views that animate from the bottom and the sliding title doesnt really fit with this.

**Comment by agarcia17** [comment]
take a look at their renderTitle function and remove any animation they apply, then you can pass your custom renderTitle function

**Comment by AndrewHenderson** [comment]
@stonepreston: @agarcia17 is correct. I recently looked into doing that very thing. I ended up going into the source code and just removing [this code](https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L437-L444) it myself, because using the `renderTitle` function would mean you'd have to recreate most of what's being done for you by the library. See: https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L407-L452

**Comment by stonepreston** [comment]
@AndrewHenderson  thanks! unfortunately removing those lines does not seem to have any effect. Ive never edited the node_modules source before. Is there something I need to do in order for the changes to be made? The file has been saved and the changes are there. I added a console.log inside the render title function and it doesnt appear to be getting called. Any ideas?

**Comment by stonepreston** [comment]
Realized I needed to re run react-native run-ios to rerun the packager and now its working great! thanks guys

**Comment by AndrewHenderson** [comment]
@stonepreston Glad to hear it. Be careful when modifying the node_modules files.

A better solution might be to just copy `NavBar.js` to your project file directory and reference that file instead. This way your repo owns the file.

Otherwise, if another engineer installed this project on his machine your code changes wouldn't be there since they are not tracked in Git.
