### ISSUE TITLE
Why doesn't navbar left button override back button?

### ISSUE THREAD

**Issue by superandrew213** [aksonov/react-native-router-flux#1547]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.2

### Expected behaviour
Providing leftTitle and onLeft should override back button 

### Actual behaviour
Back button persists.

### Steps to reproduce

Add basic router with two scenes. Give the second scene leftTitle and onLeft props.

**Comment by superandrew213** [comment]
Made PR https://github.com/aksonov/react-native-router-flux/pull/1552

**Comment by martijndeh** [comment]
This is a problem for me when rendering a sub-scene with edit mode active (in a base scene where a back button is already visible). The expected behaviour is to render a left and right button (with Cancel and Save text), instead a Back button and a Save button are rendered.

react-native-router-flux 3.37.0
react-native 0.40.0

**Comment by daviscabral** [comment]
I was getting the same issue here and I found out the answer in other issue: https://github.com/aksonov/react-native-router-flux/issues/1509#issuecomment-269825629.

> You need to override the "renderBackButton" on the Scene with a function which returns the back button. NOTE: Depending on your situation you might need to override the "renderLeftButton" instead of the back button with the same function.
