### ISSUE TITLE
master-detail example

### ISSUE THREAD

**Issue by tiagofumo** [aksonov/react-native-router-flux#1565]
### Version
- react-native-router-flux v3.37.0
- react-native v0.39.2

How people are using RNRF to build apps with master-detail that work with 2 separate screens on phones (small screens) and with a split screen on tablets (large screens). Can someone show me a sample app that has this feature, or explain a minimalist clever approach to do it? It is a pretty common pattern for apps, and I wonder what is the best way to do it.

I mean like this:
![Small screen](http://i.imgur.com/j1Dt38D.gif)
![Large screen](http://i.imgur.com/57XLTgA.gif)

**Comment by chris-at-translate** [comment]
Predefined rules set around possibly the screen size, and/or is iPad or not. Then they set the scene based on those factors. Is what I would do. Could be other ways tho.

**Comment by scblason** [comment]
I'm having a problem traying to set a navigation like this. I did a that I render a component (a list) if I'm in phone, or I render another component (list / detail) if I'm in tablet. The problem is when you want to navigate inside the detail component. How can you resolve that? You can't have a new router for the detail component. And rendering scenes inside a component (made the detail render scenes) does not work either. I want to be able to render a List / Detail component (being the list one component, and the detail another one), and then being able to click in some button in the detail, and navigate to another component, but inside the Detail view (the List component keeps rendered). Thanks
