### ISSUE TITLE
How to navigate based on a condition in RNRF react native

### ISSUE THREAD

**Issue by SiddarthG** [aksonov/react-native-router-flux#1598]
### Version

- react-native-router-flux v3.37.0
- react-native v0.40.0

I would like to navigate to new screen only if login is successful, I tried using {Actions.HomeScreen} inside if condition but it does not do anything.

here is the code:

async login() {
const res = await api.getLoginResult();
const status= res.status;
console.log('log'+status);
if(status==='success'){
  {Actions.HomeScreen;}
}

}

http://stackoverflow.com/questions/41975696/how-to-navigate-based-on-a-condition-in-rnrf-react-native

**Comment by chris-at-translate** [comment]
You are incorrectly using the actions command. Rather than `Actions.HomeScreen;` It should be `Actions.HomeScreen();` <<< Add in the () at the end. And also the extra pair of curly braces inside the if statement are not needed. Plus you could use a Promise instead of async function if you wanted too.

Thats what i think is you problem please let me know if you have any more problems.

**Comment by SiddarthG** [comment]
yes that was the problem.. thanks
