### ISSUE TITLE
Component property is not set error

### ISSUE THREAD

**Issue by natashache** [aksonov/react-native-router-flux#1604]
I'm having trouble using the router to render any component. The error message says the component is missing, but that's not true. Not sure what the problem is.

### Version
- react-native-router-flux v3.37.0
- react-native v0.40.0

### Code
```
import React, { Component } from 'react'
import { Scene, Router } from 'react-native-router-flux'
import { View, StatusBar } from 'react-native'
import Welcome from '../containers/welcome'

export class Navigation extends Component {
  render() {
    return (
    <View>
        <Router>
            <Scene key='welcome' component={Welcome} initial={true} />
        </Router>
    </View>
    )
  }
}

```
### Expected behaviour
The scene renders successfully. 

### Actual behaviour
Failed to render. The error message says "component property is not set for key=welcome".
I tried adding a root scene. It didn't work, either.

Can anybody help?

**Comment by pluxain** [comment]
Have you tried without the `<View />` surrounding the `<Router />` component ?
Are you sure you `<Welcome />` is found in the path you provide in the import statement ?

**Comment by jacenko** [comment]
Some troubleshooting steps:
1) On `import Welcome from '../containers/welcome'` it would be best to have consistent casing (so `import Welcome from '../containers/Welcome'`).
2) Inside your Welcome component, make sure you're exporting Welcome (`export default Welcome;`)
3) Make sure you have either `class Welcome extends Component {...}` or `const Welcome = () => {...}` or whichever fits your case, but with the correct spelling of Welcome.
4) Make sure your file path is correct. Is it one folder up -> containers -> Welcome?

As @pluxain mentioned, since Router is a single element, the surrounding View is most likely not needed.

**Comment by pluxain** [comment]
I suggest using [this tip](https://github.com/facebook/react-native/issues/3099#issuecomment-221815006) to clean imports rather than use relative paths. Read more about this [here](https://medium.com/@davidjwoody/how-to-use-absolute-paths-in-react-native-6b06ae3f65d1#.neok1pcvv)

In your case, that would mean to place a `package.json` file in the `containers` folder and add this code inside :
```json
{
    "name": "containers"
}
```

Then in your `import` statements you can use directly this from where ever you are :
```javascript
import Welcome from 'containers/Welcome';
```

You can further improve the includes by adding and `index.js` files in the `containers` folder and list in it all your containers like so:
```javascript
// containers/index.js
export { Welcome } from './';
```

This way you can then include things like this :
```javascript
// Navigation.js
import Welcome from 'containers';
```

To have the index file export working you need to use `export class Welcome` or `export const Welcome` rather the `export default` syntax.

**Comment by natashache** [comment]
Thanks everyone for the tips. I checked again and the components were correctly imported. I also tried using react-navigation (https://reactnavigation.org) as an alternative navigator, and it's able to pick up the imports with no problem:

```
import { Welcome } from './containers/Welcome'
import { Signup } from './containers/SignupScreen'
import { Main } from './containers/Main'

import { StackNavigator } from 'react-navigation';
import { Scene, Router } from 'react-native-router-flux'

export const NavigationAlt = StackNavigator({
  Home: { screen: Welcome },
  Signup: { screen: Signup }
});

export class Navigation extends Component {
  render() {
    return (
      <Router>
        <Scene key='Welcome' Component={Welcome} initial={true} />
      </Router>
    )
  }
}
```
In the above file, when I comment out the Navigation class and use NavigationAlt, which uses react-navigator, the component shows up. But when I try to use Navigation, it gives me the error that component for 'key=Welcome' is not set.

Not sure what the problem is. Thinking of just switching to react-navigator.

**Comment by byennen** [comment]
@natashache same issue.

**Comment by natashache** [comment]
@byennen react-navigation has been working for me so far. Don't know when the other shoe is going to drop, but not going to hold my breath for that :)

**Comment by chris-at-translate** [comment]
Have you tried to se the component to be exported as default so...` export default class` Plus also can you show where you have linked this file to your index.ios.js and index.android.js files.

**Comment by Abdul-majid-ashrafi** [comment]
I am also facing this issue

**Comment by UrbanChrisy** [comment]
@Abdul-majid-ashrafi Please open a new post on stack overflow with your code and any errors that are happening, its not a bug but a user error.

**Comment by Abdul-majid-ashrafi** [comment]
Alrigth
