### ISSUE TITLE
Gesture threshold problem

### ISSUE THREAD

**Issue by mjt19930301** [aksonov/react-native-router-flux#1715]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

### Expected behaviour

Gesture operation, right slide, within 30px  trigger, you can slide to the previous page

### Actual behaviour

Close to the left 0px  position to trigger

Thank you

**Comment by Kowaio** [comment]
Hi guys,
I'm using router-flux v3.31.2 and I've got a problem swiping back on iOS. The maximum threshold respond position is 30px due to the `NavigationCardStackPanResponder`class from `react-native-experimental-navigation` (https://github.com/aksonov/react-native-experimental-navigation/blob/master/NavigationCardStackPanResponder.js#L47). Is there a way to change that programmatically ? It is very hard to trigger the swipe back gesture.

Thanks a lot for your help!

**Comment by mjt19930301** [comment]
Thanks a lot for your help!
