### ISSUE TITLE
tabs re-rendering when switching in 3.38.0

### ISSUE THREAD

**Issue by blackPeanut** [aksonov/react-native-router-flux#1725]
### Version
Tell us which versions you are using: 
- react-native-router-flux v3.38.0
- react-native v0.35.0

### Expected behavior
Expected switching between tabs without triggering mount functions.

### Actual behavior
New version 3.38.0 unmounts tabs when switching between them, which triggers willMount/didMount functions when switching back again to previous tabs.

I think this info should be documented in release notes/documentation as breaking changes/new behavior.

**Comment by henrythach** [comment]
@blackPeanut Try adding `type={ActionConst.REFRESH}` to the `<Scene>`.

I was having the same issue with react-native-router-flux v3.38.0 + react-native v0.42.0 and this worked for me.

Props to https://github.com/aksonov/react-native-router-flux/issues/1686.

**Comment by Lughino** [comment]
Insert `type={ActionConst.REFRESH}` causes multiple problems:
* back button is rendered in all tabs child
* call any scene outside tabs has no effect (call `JUMP` and `REFRESH` actions)

**Comment by blackPeanut** [comment]
Thanks guys @LiangQiao @henrythach. But this issue is more about updating docs, than solving this breaking change  :)

**Comment by ays0110** [comment]
@blackPeanut I'm not sure that this change was intentional...  I think they tried to implement something that would pop back to initial state when the tab active and then tapped again (https://github.com/aksonov/react-native-router-flux/issues/717), but then accidentally made a change that does even when the tab is not active.  Hoping they'll change it back or make it compatible with both kinds of use cases (ideal!)
