### ISSUE TITLE
Mount functions not working properly when switching tabs

### ISSUE THREAD

**Issue by GuillaumeMunsch** [aksonov/react-native-router-flux#1731]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.3

### Expected behaviour

I have 2 tabs right now. I'd like to call a specific function every time I arrive on one of these tabs, in the componentWillMount method if possible.

### Actual behaviour

I tried to do so but the behavior is kind of weird. Let's say I have 2 tabs A and B. When I launch my app, A is mounted and my function is called. I switch to tab B, tab B is mounted and my function on tab B is called. I switch back to A, A is unmounted and re-mounted, my function is called. Until now, everything worked as expected but when I switch back to B, B isn't unmounted and re-mounted and my function isn't called because B's componentWillMount function is not called. From now on, none of the componentWillMount or componentWillUnmount is called on any of both tabs and I can't call my function.

I feel like I have the exact opposite behavior of that guy's issue: https://github.com/aksonov/react-native-router-flux/issues/1725

Thanks in advance :)

**Comment by GuillaumeMunsch** [comment]
Hi !

Any news on this ?

**Comment by vincicat** [comment]
Check the issues with "lifecycle" will show you the fact that `RNRF` does not run the lifecycle methods during tab switching, lifecycle method is called only when:
1. props change (made by react-redux's `mapStateToProps` or passing props when loading tabs)
2. RN unmounted it for saving memory

Some solutions suggest using your own reducer, or changing the component logics. 

**FYI**
The non-redux Solution is not well mentioned in the docs, require override onPress function of tab (scene with `icon`) in order to pass your own parameter: 
https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#tabbar
```
  <Scene 
    key="myTab" 
    title="My Tab" 
    icon={MyTabIcon} 
    onPress={()=> {
      Actions.myTab({propsToPass});
    }}
   >
     //...Available Scenes inside "My Tab"...//
  </Scene>
```

**Comment by GuillaumeMunsch** [comment]
Thanks for pointing out the `onPress` method.  It's not well mentioned in the doc (https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md) as you said it :/. Maybe this should be ...

Either way, thanks :)
