### ISSUE TITLE
Swipe back is flaky

### ISSUE THREAD

**Issue by jorilallo** [aksonov/react-native-router-flux#176]
Not really sure what's the issue, but swipe back actions seem to be extremely flaky: they work roughly 3-50% of the time which is extremely frustrating. Any idea why this might be?

**Comment by aksonov** [comment]
I thought it should not work at all with current version :) Check what animations you are using (sceneConfig). Animations.FlatFloatFromRight disables it at all. The reason - i can't find how to override 'pop' behavior for swipe - I need to call Actions.pop() because built-in pop will not update current router, its stack, etc. Any help would be appreciated here to fix it.

**Comment by lynndylanhurley** [comment]
I just created a Product Pains post for this. Please upvote:
https://productpains.com/post/react-native/override-swipe-back-behavior/

**Comment by aksonov** [comment]
This issue should be fixed in upcoming 3.0 release of this component #186

**Comment by rampazzo1989** [comment]
Any updates?
