### ISSUE TITLE
How can I access state within renderNavigationBar?

### ISSUE THREAD

**Issue by Rogergonzalez21** [aksonov/react-native-router-flux#1763]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37
- react-native v0.41.1

### Expected behaviour
To be able to use my state inside renderNavigationBar

### Actual behaviour
I can't access state

I need to display a button based from a boolean value that is inside my state, but I can't access it because `renderNavigationBar` is a `static` method. If someone has worked around this, that would be great.

Thanks.

**Comment by foggy1** [comment]
It's a dirty workaround, but you need to Actions.refresh({ your state here }) to load it in as, props, which you can then access.  There is no cleaner workaround since it is a class method that will not have access to the instance's state.

If you find that to be too funky or inconvenient, I would recommend hiding the navbar and just making your own navbar component to render in instances of your components without this issue.
