### ISSUE TITLE
How to insert a newline to Title

### ISSUE THREAD

**Issue by anceque** [aksonov/react-native-router-flux#1896]
### Version
- react-native-router-flux v3.39.1
- react-native v0.44

### Question
I need to render a title with a subtitle on a screen which is being updated through refresh action. 

I created a custom component which i inserted into `Actions.refresh(title: <CustomComponent>)`.

My original simplified code inside of `render()` function of `CustomComponent`:
```
<View>
   <Text>Title</Text>
   <Text>Subtitle</Text>
</View>
```

This worked in `iOS` and it was smooth. 
Apparently, the title of the navBar is rendered as a `<Text>` component, so `Android` says that i cannot render a `View` inside of `Text`. so i needed to change my code into something like:
```
<Text>
   <Text>Title</Text>
   {'\n'}
   <Text>Subtitle</Text>
</Text>
```
The problem is that this is rendered in one line. I tried to insert a newline but in Android, it is displayed as whitespace and the text is still in one line. In iOS, the second line is somewhere behind the navbar.

i even tried to write it as `<Text>Title\nSubtitle</Text>` or other solutions mentioned here:
https://stackoverflow.com/questions/32469570/how-can-i-insert-a-line-break-into-a-text-component-in-react-native

Has anybody run into similar problem?

My desired outcome is something like:

![image](https://cloud.githubusercontent.com/assets/2404343/26459417/ae7442ea-4176-11e7-80f2-9d9248a1581d.png)

**Comment by ReactDevBeginner** [comment]
Hello everyone

Please I use native base, I want to skip the line after "Analyst", I used the code above.

To jump the line I used: {'\ n'} between the two lines.
The problem is that I can not change the margin between the text?
![image](https://user-images.githubusercontent.com/38378058/43358694-ac358a98-928d-11e8-8b63-84bf17199247.png)
![14884b0e-6d2a-4441-a391-3257f550bb69](https://user-images.githubusercontent.com/38378058/43358699-bc074376-928d-11e8-81a1-39de53e12b6a.jpg)

Thanks
