### ISSUE TITLE
Trying to render any other type of tab bar leads to layout issues

### ISSUE THREAD

**Issue by MaxwellGover** [aksonov/react-native-router-flux#1984]
### Version
Tell us which versions you are using (v4 is only supported, check latest beta '4.0.0-beta.x') : 

- react-native v0.46

### Expected behaviour

Rendering `<TabBarIOS>` or any other tab bar from another library would render correctly. 

### Actual behaviour

Rendering tab bars leads to weird layout issues where only half of the expected scene is visible.

### Steps to reproduce

1. Try wrapping Router in a view w/ a flex of 1
2. Add TabbarIOS after closing Router tag and before closing View tag.

<img width="376" alt="screen shot 2017-07-07 at 7 53 32 pm" src="https://user-images.githubusercontent.com/11525891/27980597-64016626-634e-11e7-9a37-7b4d718636ee.png">

**Comment by MaxwellGover** [comment]
Adding a `<View>` tag instead of a TabBar w/ a height of 60 and background of black works fine.

<img width="371" alt="screen shot 2017-07-07 at 7 57 16 pm" src="https://user-images.githubusercontent.com/11525891/27980612-8c86c1cc-634e-11e7-948c-fe9a3b0310f6.png">

**Comment by aksonov** [comment]
External TabBar is not supported - because it is not supported by React Navigation. You have to provide own custom navigator to make it work:
https://reactnavigation.org/docs/navigators/custom
and pass it as `navigator` prop to `Scene`.

Or you may just copy their TabNavigator and change code appropriately.
