### ISSUE TITLE
Confusion to new comer: what version shall I use?

### ISSUE THREAD

**Issue by oeddyo** [aksonov/react-native-router-flux#2041]
Thanks for the great work of putting up this amazing tool together. 

As a new comer to this tool, I'm overwhelmed by the version changes and on going doc improvements. My question is, since V4 is in beta, and a lot of APIs are changing (correct me if I'm wrong), what version shall we use in production?

Thanks!

**Comment by oeddyo** [comment]
To be more specific, in V3's doc page, the API page is giving 404. And in V4's doc page, seems the author is still working on it :|

**Comment by diegocouto** [comment]
Hi, @oeddyo I think that it depends on what you're building. If it's an iOS only app, I'd definitely go with v4 (React Navigation transitions are a delight). On the other hand, if you need Android compatibility, v4 can't be used without workarounds.

**Comment by oeddyo** [comment]
Thanks a lot @diegocouto for commenting!

We are actually building for both android & ios. Thus I guess the option for us is to go with v3 then... 

Thank you!

**Comment by aksonov** [comment]
@oeddyo I see your confusion - v4-beta or unsupported-v3. This problem is going from quite strange React Native team behaviour - stop to support existing navigation and ask community for migration to _beta_ ReactNavigation package. So I v4-beta is the same quality as _beta_ React Navigation. If it works differently for Android compare to React Navigation then it is VERY strange because RNRF is just wrapper - you may check source codes - it just creates needed component tree and configuration for ReactNavigation. Probably the problem that Android doesn't support passing functions/images as parameters to actions (because images are passing now via props)? It is necessary just to debug it to find the reason...
