### ISSUE TITLE
How to push routes into tab from outside the tab router

### ISSUE THREAD

**Issue by amrnt** [aksonov/react-native-router-flux#209]
I found that the guys here: https://github.com/Qwikly/react-native-router-redux implemented a way to push routes from out side tab router into the current tab. So no need to repeat all routes that are going to be used inside the tab across all tabs. I hope I'm not wrong and I didn't miss anything.

Look here (in action): https://github.com/Qwikly/react-native-router-redux/blob/master/example/ReduxRouter/app/containers/app.js#L58-L64 and https://github.com/Qwikly/react-native-router-redux/blob/master/example/ReduxRouter/app/components/Master.js#L11-L14

**Comment by aksonov** [comment]
These guys 'copied' my component, added redux support and called it 'inspiration'...
Ok, I don't know why you wrote about this "component" here and why you can't use the same here - define come component in root and push it from inner route?

**Comment by amrnt** [comment]
Com'on mate! It's obvious that they copied your code and called it 'inspiration'! And no one should their "component" since -at least- its not a "fork" of this project... and mentioning this here means how good is `react-native-router-flux` comparing to other `react-native-router` out there.

What I mean In my question: calling "an action from outside tabs router" doesn't render the component inside the current tab... or?

**Comment by aksonov** [comment]
Oh, could you give use case? Currently it renders 'root' route outside tab bar...

**Comment by amrnt** [comment]
`feed tab -> single item -> user profile`
`feed tab -> single item -> comments list -> user profile -> user posts -> comments -> other user`
`notification tab -> single item -> user/comments ->  ...`

Each view above represents a route...

```js
<Router name="root">
    // ...
    <Route name="profile" component={Profile} title="Profile"/>
    <Route name="single_post" component={SinglePost} title="Post"/>
    <Route name="comments" component={Comments} title="Comments"/>

    <Route name="tabbar">
        <Router footer={TabBar}>
            <Route name="feed" schema="tab" title="Feed" component={Feed} />
            <Route name="notification" schema="tab" title="Notification" component={Notification} />
        </Router>
    </Route>
</Router>
```

**Comment by Elyx0** [comment]
Came around the same issue where you can't call a nested tab route from outside the tab have to repeat the routes that are going to be used inside the tab across all tabs. I thought it was build in and I was doing something wrong.

**Comment by ChaitanyaBudapaneti** [comment]
When I come out of the **Login** modal view using the back button calling the ``` Actions.pop()``` method everything works fine. But when using the slide down gesture to close the Login modal, the router doesn't return to the **TabBar** router. This gives me an error when I press on Tabs.

```
<Router hideNavBar={true} name="root">
        <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
        <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
        <Schema name="withoutAnimation"/>
        <Schema name="tab" type="switch" icon={TabIcon} />
        <Route name="tabbar">
          <Router footer={TabBar} showNavigationBar={false}>
            <Route name="tab1" schema="tab" title="Tab #1" component={MyListView}/>
            <Route name="tab2" schema="tab" title="Tab #2" component={Launch}/>  
          </Router>
        </Route>
        <Route name="LoginView" component={Login} schema="modal" wrapRouter={true}/>
</Router>
```

**Comment by Elyx0** [comment]
Made a bit of digging:
Let's say we're in a context like 1root route, 1 tabbar with nested routers:
```javascript
<Route name="tutorial"  initial={true}   hideNavBar={true} title="Tutorial"  component={TutorialView} />
<Route name="tabbar">
  <Router  footer={TabBar} showNavigationBar={false}>
    <Route name="browse" schema="tab" title="th-list">
      <Router name="br_rooter">
        <Route name="b1" component={BrowseSwitcher}  />
        <Route name="b2" component={MyComponent}  />
      </Router>
    </Route>
    <Route name="me"  schema="tab" title="user">
      <Router name="me_rooter">
        <Route name="m1" component={MeSwitcher}   />
        <Route name="m2" component={MyComponent}   />
    </Router>
    </Route>
    <Route name="friends" schema="tab" title="list-alt">
      <Router name="fr_rooter">
        <Route name="f1" component={FriendsSwitcher} />
        <Route name="f2" component={MyComponent}  />
      </Router>
    </Route>
  </Router>
</Route>
```
From the Tutorial route, after the user finishes the tutorial I **can't**:
`Actions.friends()`
`Actions.m1()`
Otherwise triggering `_reactNativeRouterFlux.Actions.friends is not a function`

I only can:
`Actions.tabbar()` that will then mount the `browse` route that will then mount the `br_router` that will instanciate my `BrowseSwitcher` component.

This `BrowseSwitcher` is allowed to navigate only to its direct children or some siblings such as `Actions.me()` and `Actions.friends()`. But even from here, I can't ask it to load a further nested route like `Actions.f1()`.

Only solution is to use every first route inside nested tabbar routers as "Switcher" routes, that determine where the user wants to go... which is a pain..
Frome `m1` for example, I have to do `Actions.me({goto:'m2'})` then `MeSwitcher` will pick the goto param and issue a `Actions.m2()`.

Note:  That switch can't happen too fast either, it has to be in the `componentDidUpdate` or the flow of actions will be cut too early, causing an error.

Trying to solve `_reactNativeRouterFlux.Actions.friends is not a function` is not easy, I tried a quick test-patch in `_addActions` to add the missing actions first.

```javascript
    _addActions(){
        if (!Actions.currentRouter){
            Actions.currentRouter = this;
            debug("Set current router:"+this.name);
        }
        console.log(Actions.currentRouter,Actions);
        // Are we in a tab children
        if (this.parentRoute && this.parentRoute.type == "switch"){
          //Add parent parent children routes actions if exists.
          if (this.parentRoute.parent){
            const childrenRoutes = this.parentRoute.parent.routes;
            const childrenKeys = Object.keys(childrenRoutes);
            if (childrenKeys.length > 1){
                 childrenKeys.forEach(name=>{
                   if (name != this.parentRoute.name){
                       const siblingRoute = this.parentRoute.parent.routes[name];
                       siblingRoute.children.props.children.forEach(children =>{
                         const name = children.props.name;
                         if (!Actions[name]) {
                         Actions[name] = function(data){
                             return Actions.route(name, data);
                         }
                       }});
                     }
                 });
            }
          }
        }
        Object.keys(this.routes).forEach(name=>{
            if (!Actions[name]){
                Actions[name] = function(data){
                    return Actions.route(name, data);
                }
            }
        });
    }
```

And then a second problem came along is that `Actions.js` only tries children or parent router from where it is called, not `siblings` routers. So we need to help him find the correct Router that hold the tab we watch to switch to from another tab.


```javacript
    route(name: string, props: { [key: string]: any} = {}){
        if (!this.currentRouter){
            throw new Error("No current router is set");
        }
        if (props.toString()!='[object Object]')
            props = {data : props};

        props = filterParam(props);
        // check if route is in children, current or parent routers
        let router: BaseRouter = this.currentRouter;

        // deep into child router
        while (router.currentRoute.childRouter){
            router = router.currentRoute.childRouter;
            debug("Switching to child router="+router.name);
        }

        debug("Route to "+name+" current router="+this.currentRouter.name+ " current route="+this.currentRouter.currentRoute.name);
        while (!router.routes[name]){
            const route = router.parentRoute;
            //Check Siblings routers.
            const siblings = route.parent &&
                             route.parent.parentRoute &&
                             route.parent.parentRoute.childRouter &&
                            route.parent.parentRoute.childRouter.routes;
            const {[route.parent.currentRoute.name]:_, ...otherSiblings} = siblings;
            const foundInSiblings = Object.keys(otherSiblings).some(sibling=>{
              const childRouter = route.parent.parentRoute.childRouter.routes[sibling].childRouter;
              if (childRouter && childRouter.routes[name]){
                    router = childRouter;
                    debug("Found in siblings="+router.name,router);
                    return true;
                  }
                  return false;
            });

            if (!route || !route.parent){
                throw new Error("Cannot find router for route="+name+" current router="+router.name);
            }
            if (!foundInSiblings) router = route.parent;
            debug("Switching to router="+router.name);
        }
```

And It somehow worked... But only if you visited the route once before, causing `childRouter` to belong to the route object. Otherwise it's undefined until the route is visited. And even with doing all that, it only switches the tab, but not `TO THE` tab. If I was on `b1` and calling `Actions.f2`, the `fr_router` will indeed be switched to `f2` but I will not be moved from `br_router` to `fr_router`.

Aaaand that's it so far. I think the library owners could help us in the correct direction.

**Comment by uyson** [comment]
+1 same problem

**Comment by aksonov** [comment]
I could suggest to implement some kind of Route 'ref' which will 'clone' some 'root' Route during Router initialization. Maybe someone could implement it, it should be quite easy. Will it solve this problem?

**Comment by aksonov** [comment]
Please check latest 3.0 release. Closing this ticket for now (because it is for outdated 2.x)

**Comment by amrnt** [comment]
@aksonov May you add this to the example? I'm having terrible time trying to understand/implement it :(

**Comment by joenoon** [comment]
@aksonov great library!  I think I'm running into this same issues here.  Can you tell me if there is a way to do this?

```
const scenes = Actions.create(
  <Scene key="root" hideNavBar={true}>
    <Scene key="apples" component={View} title="apples" />
    <Scene key="oranges" component={View} title="oranges" />
    <Scene key="tabbar" initial={true} tabs={true} default="tab1" >
      <Scene key="tab1" component={View} title="Tab #1" icon={TabIcon} initial={true} />
      <Scene key="tab2" component={View} title="Tab #2" icon={TabIcon} onRight={() => Actions.apples()} rightTitle="Push" />
    </Scene>
  </Scene>
);
```

What I'd like to happen is when I call `Actions.apples()`, I want it to push inside tab2 (the currently active scene).

Right now, it renders over the entire tabbar, which is true to how its defined above, but not how I'm hoping to use it.

One option is to redefine apples and oranges inside of each tab (tab1_apples,tab1_oranges,tab2_apples,tab2_oranges).  The problem with this is I need to know which tab I'm currently in to know the key.  ```Actions[`${currentTab}_apples`]()```.

Is there another option, to just push into the currently active context?

**Comment by joenoon** [comment]
I found a partially working solution: `Actions.apples({parent:'tab2'})`

That gets the scene rendered in the current tab, but still has some downsides:

- The back button doesn't work, probably because...
- `Actions.pop()` doesn't work.  But this works: `Actions.pop({parent:'tab2'})`

If I were to keep going down this road my plan would be to write a wrapper taking in the navigationState.  Something like `Actions.inContext(this.props.navigationState, Actions.apples)` and the same for pop.  But I'd like your thoughts on if this even seems like the right way to approach it (manually overriding `parent`).

**Comment by aksonov** [comment]
I propose to implement pushToCurrent type which will add scene to current parent - like pop removes _current_ scene, pushToCurrent will push to current scene. So Reducer will replace parent to current one so pop() should work.

PR is welcome.

**Comment by joenoon** [comment]
PR here: https://github.com/aksonov/react-native-router-flux/pull/389

**Comment by aksonov** [comment]
@joenoon Pleas check 3.2.0 version. I did huge refactoring to optimize state management, hope you could implement your change easier now.

**Comment by aksonov** [comment]
@joenoon please check latest 3.2.3, i've simplified your PR, maybe too much?

**Comment by joenoon** [comment]
@aksonov Ya thats exactly what I was just trying here.  It almost works, but one of my actions is getting parent 'root' for some reason, so I'm trying to track that down.  That is one from a navbar where I do refresh in the componentDidMount (which is amazing!).  But otherwise clicking around seems to work like this.  I'll track down the problem I'm having and see if I run into any other issues! Thanks!

**Comment by jdmunro** [comment]
Just wondering if this solution was ever implemented?

**Comment by toadums** [comment]
@jdmunro give your routes the `clone` property, and they can be pushed in any tab. 

```
<Scene key="root">
  <Scene key="tabs" tabs>
    <Scene key="Account" />

**Comment by Naoto-Ida** [comment]
@toadums Thanks for pointing this out. Finally figured out the last issue on our app's issues list.

**Comment by mrbarde** [comment]
@jdmunro  what worked for me was to do `Actions.Tabs()` using  @toadums  code as example above, that way it loaded the first scene in the tabs scene, problem solved for me!

**Comment by fostertime** [comment]
I fought this issue for 2 days... turned out that `clone` does not work correctly if the root scene is wrapped with a `modal` component. Has anyone figured out a workaround for this?
