### ISSUE TITLE
react-native-drawer example with react-native-router-flux 4

### ISSUE THREAD

**Issue by vijaychouhan-rails** [aksonov/react-native-router-flux#2133]
Can you please provide me an example of react-native-drawer with react-native-router-flux 4

**Comment by aksonov** [comment]
v4 uses built-in react-navigation drawer.

**Comment by vijaychouhan-rails** [comment]
@aksonov 

I know but I want to use react-native-drawer because I need to use displace screen feature but in-build drawer does not provide this.

**Comment by aksonov** [comment]
Try new `overlay` and `contentComponent` props (not documented, will be useful for PR about documentation):
```
<Scene overlay contentComponent=`CustomDrawer`>
   <Scene>...</Scene>
   <Scene>...</Scene>
   <Scene>...</Scene>
</Scene>
```

Within `CustomDrawer` you define all drawer. The question is how to call drawer open/close... We need to think about it, but try this first.

**Comment by raynor85** [comment]
I have successfully implemented it. The CustomDrawer must specify this.children.props in order to display its nested Scenes. The only problem I am experiencing now is removing the animation transitions. In my implementation, using type="reset" to <Scene overlay contentComponent=`CustomDrawer`> avoid the initial transition. Maybe the approach mentioned here could be useful to get rid of unwanted animated transitions.
https://github.com/aksonov/react-native-router-flux/pull/2062

**Comment by themakerman** [comment]
@raynor85 What does overlaycontentComponent prop does to the Scene?

**Comment by foyarash** [comment]
Hello,

I don't receive the children in the props, how can I retrieve them?

**Comment by raynor85** [comment]
@foyarash, maybe this is related to https://github.com/aksonov/react-native-router-flux/issues/2496
Try the version beta.17, since the overlay seems to be removed in beta.18, and let me know

**Comment by raynor85** [comment]
@themakerman it is just a wrapper used to add a component in the top of the app

**Comment by foyarash** [comment]
OverlayNavigator is actually present in beta.22

**Comment by raynor85** [comment]
@foyarash OverlayNavigator is indeed present in beta.22, but no longer accept contentComponent as a prop. My pr #2578 solves that.

**Comment by mightym** [comment]
How do I receive the the children there?
