### ISSUE TITLE
All tab view of tabs are mounted once.

### ISSUE THREAD

**Issue by lazyhoneyant** [aksonov/react-native-router-flux#2197]
### Version
Tell us which versions you are using:  

- react-native-router-flux 4.0.0-beta.16
- react-native 0.45.1

I have tabbar which have 4 tabs.

When I enter the first tab of tabbar, other tabs are mounted ( checked this in componentDidMount life cycle function)

Additionally, When I pressed another tab, old tab view component was not unmounted.

Is it normal behavior?

This makes App to call unnecessary API calls.

**Comment by giulianok** [comment]
Same here

I had to move the `<Scene>` to the tab component, return it inside of a function and call it where I need the scene. Then, I used `onEnter` instead of `componentWillMount` or `componentDidMount`.

I can show you the code if you need it

Besides, we should have the option to not mount the components until we enter

**Comment by lazyhoneyant** [comment]
@giulianok 
I want to see your codes.
You mean that to work around this bug(?) you use 'onEnter' method. right?
I think so that we need to option to not mount the components until we actually enter. 
When a tab is switched to another scene, previous tab component needs to be unmounted too.

**Comment by aksonov** [comment]
@lazyhoneyant Use `lazy` option. Will add it to docs. Component will NOT be unmounted after switching - it is how tabbar works.

**Comment by lazyhoneyant** [comment]
@aksonov 
thank you. 'lazy option' solves this problem.
