### ISSUE TITLE
Maintain own fork of react-navigation?

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#2276]
Hey guys,

Many bugs exist in react-navigation for months and it happens even with proposed PRs that fix some critical issues (like https://github.com/react-community/react-navigation/pull/793). What do you think if RNRF will use forked react-navigation with most useful PR merged? Downside will be possible conflict with upcoming beta.12 but its release date is unknown...

**Comment by luco** [comment]
I think it's a great idea, since many of current v4 issues are related with react-navigation. 
It would be nice to merge the best PR's from react-navigation.

**Comment by aksonov** [comment]
Please list PR here to merge.

**Comment by aksonov** [comment]
https://github.com/react-community/react-navigation/pull/1803 to fix #2144

**Comment by aksonov** [comment]
https://github.com/cribspot/react-navigation/commit/02a12045ef50550fcec5187466cedd0cb206d259 to fix #2012

**Comment by luco** [comment]
Maybe this: https://github.com/react-community/react-navigation/pull/2222

**Comment by Amurmurmur** [comment]
I think one of the most important PRs is the one that fixes slow transitions on android.

For instance this issue: https://github.com/react-community/react-navigation/issues/608

**Comment by aksonov** [comment]
Where is that PR?

**Comment by Amurmurmur** [comment]
Sorry, I think this approach fixes the issue: https://github.com/react-community/react-navigation/issues/706#issuecomment-295322551

**Comment by RWOverdijk** [comment]
👍  I've been patient for long enough now. Which is annoying if you could actually help, but it then doesn't get merged.

**Comment by aksonov** [comment]
@RWOverdijk Welcome to RNRF! I'm trying to merge all PRs if they are useful.

**Comment by RWOverdijk** [comment]
@aksonov I got that :p I'm not new here, see how it says contributor? Haha.

That's a good idea. At least until it can be merged back / they create a board of more diverse members to allow for a better flow of progress.

**Comment by davojan** [comment]
per-scene (not per-navigator) modal configuration
https://github.com/react-community/react-navigation/pull/2308

**Comment by charpeni** [comment]
I'm not a big fan of splitting community like this, neither unmerged PRs. IMO, PRs should be merged in their respective repositories.

I just shared this with react-navigation team.

**Comment by spencercarli** [comment]
I would have to agree with @charpeni here - I'm not a huge fan of splitting because it would greatly increase confusion for anyone getting started (do they choose React Navigation, react-native-router-flux, react-native-router-flux's fork of React Navigation --- in addition to the plethora of options already out there).

That being said I understand the desire/need to fork react-navigation for certain things, and especially the frustration with fixes not landing in master & new releases. Fortunately the project has some [new blood](https://github.com/react-community/react-navigation/pulse/monthly) that's pushing the project forward. The original maintainers have _a ton_ of projects (that are heavily relied on by the community) but only have so much time, thus react-navigation has fallen a bit behind.

As you can see by the project pulse a lot of issues have been closed over the last few weeks! That's our primary goal right now - get out from under the mountain of issues - and we're almost there!

Here's a quick run down of our game plan:

1. Triage all issues
2. Close duplicate issues
3. Merge "easy" PRs (documentation, small bug fixes)
4. Figure out new path to 1.0 (what bugs exists, most requested features - the links you all have posted are very helpful in weighing that)
5. Start merging PRs/putting together PRs that get us closer to 1.0
6. Repeat step 5 until completion
7. Release 1.0 🎉 

It's definitely a process and the new contributors (myself included) are still getting ramped up so it's taking us a bit of time but I hope that you see the project is coming out of hibernation and we want to put together an incredible navigation solution.

**Comment by charpeni** [comment]
Thanks @spencercarli.

I now have push access to [react-navigation](https://github.com/react-community/react-navigation), feel free to ping me if there're any pull requests blocking you.

**Comment by hysan** [comment]
@charpeni Could you go through all of the PRs that have been linked in this issue and merge them? It would be a great start and restore confidence in the original project to see long standing PRs finally being addressed.

**Comment by D1no** [comment]
Has the situation improved since? We are in the situation to drop RNRF v3 because RN 49 uses react 16, which has no more the depreciated prop-types. Hence, react-native-router-flux v3 wont compile.

Now we have to update / switch. I looked into V4 and as it seems, conditional tab hiding does not work. That is a blocker for us. From the migration guide this issue still persists.

We would love to stay with RNRF because of the native redux integration; but are now evaluating to switch to https://github.com/wix/react-native-navigation due to **0 confidence into the proper maintenance of react-navigation**. On the other hand, react-native-navigation is in a "do it yourself" redux state and in the middle of v2.

Any advise?

**Comment by stereodenis** [comment]
@D1no look at
https://github.com/react-community/react-navigation/issues/2585
and
https://github.com/react-community/react-navigation/pulse/monthly

**Comment by D1no** [comment]
Thanks @stereodenis — the progress looks promising. Two things I still worry about:
- Has the [performance problems on android](https://github.com/react-community/react-navigation/issues/2585#issuecomment-331621399) been addressed lately?
- Is the problem with tabBarHiding solved? 

That is not very eminent to see from the contribution pulse. All this would be easier of course, if RNRF would support other navigator engines — such as wix/react-native-navigation.

**Comment by vonovak** [comment]
@D1no I personally don't see any perf problems with react-navigation on android, and my app isn't all too simple. It may be the problem wasn't with the library but with the people's code. Also make sure to not run the code in dev mode if testing for perf...
