### ISSUE TITLE
Jump to specific scene

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2335]
I want to jump to a specific scene in a specific scenario. But when I do, the previous scene is in stack.
E.g.:
```
<Scene key="signup"}>
    <Scene key="signUp1" title="Title"  component={Scene1}/>
    <Scene key="signUp2" title="Title"  component={Scene2}/>
</Scene>
```

I want to jump to signUp2, but without putting signUp1 in stack. Is that possible?
When I do that, my back button points to signUp1 and not to the previous scene.

Thanks

**Comment by mcabs3** [comment]
@luco if `signUp1` and `signUp2` aren't related to work in a `Stack` pattern, then I would ask why you would have them in a group `Scene`?

I think a simple fix would be to pull those two out of the group. I think what is happening is it is behind the scenes loading `signUp1` in the stack because it is technically the `initial` route for your `signup` Scene.

**Comment by aksonov** [comment]
You have to use `Tabs` element or `tabs` param for 'jumping'
