### ISSUE TITLE
Router check for loading prop

### ISSUE THREAD

**Issue by enguerranws** [aksonov/react-native-router-flux#2387]
Hi,

I'm not reporting an issue, just suggesting a possible improvment. Would it be possible to implement a property that the Router is listening so it renders a loading overlay?

Something like:
`<Router style={styles.router} isLoading={this.props.loadingStatus}>`

Or a HOC. I know there's a ton of examples which show how to do that, but I think this would be a good option/helper in this lib.

**Comment by mcabs3** [comment]
I think if you do this, you would force people using this library to implement Redux/Mobx so that the loading state could be controlled globally. I personally think a better approach would be to create some `<Screen />` component with a isLoading prop that can be adjusted with local state or a global state management system.

**Comment by aksonov** [comment]
It is not supported
