### ISSUE TITLE
Navigation Component re-mounts when app is re-entered on Android

### ISSUE THREAD

**Issue by jasongrishkoff** [aksonov/react-native-router-flux#2469]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0.beta21
- react-native v0.48.0

### Expected behaviour

When I minimize / set the app to background and then return, it should not reload everything -- just resume from where it is.

### Actual behaviour

The Tab components all remount and everything reloads. Setting the app to singleTask or singleInstance, as suggested in #1915 does not seem to resolve the issue.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Open app
2. Minimize app / set it to background (do not close the process)
3. Re-open the app

**Comment by jordanfloyd** [comment]
So I don't think this is an issue with this library as much as it is with Android and React Native. The behavior is actually different if you press the hardware back arrow than if you press the circle (minimize), at least for us. So what is happening is that the root component of React Native is getting unmounted when you use the backArrow instead of the circle, so you have to handle this case just like an app launch. There are tricks you can do like hook into the componentDidMount of the root component to know when its a launch vs a resume.

If someone hasn't had this issue or has an easier solution, I'd be interested to see how their app is setup.

**Comment by alexwasner** [comment]
I'm running into this same issue and @jordanfloyd is correct on the back vs the circle for my case as well. Just subscribing to this to see if anyone has any solutions. I tried putting a hack in componentDidMount with a key on my AppState store, and while it fixes the issue, it seems I now have a ghost `Router` hanging out in cyber space listening to events and causing issues.

**Comment by aksonov** [comment]
@jasongrishkoff Could you check react navigation core examples?
