### ISSUE TITLE
Shared element transition animation

### ISSUE THREAD

**Issue by shukerullah** [aksonov/react-native-router-flux#2589]
Shared element transition animation feature required in `react-native-router-flux`, its is possible with `react-navigation`. 

Here is reference:
[react-navigation-shared-element-transition](http://www.reactnativediary.com/2017/04/22/react-navigation-shared-element-transition-3.html)

![giphy 1](https://user-images.githubusercontent.com/963765/32383205-273138aa-c0d9-11e7-96bc-7c0f3f37dd1e.gif)

[Youtube Link](https://www.youtube.com/watch?v=LJl0hNzoWmg)

**Comment by aksonov** [comment]
If RN supports it you can use it with RNRF as well. Feel free to submit PR if you feel it could be done in more easier way...

**Comment by aksonov** [comment]
Great https://github.com/fram-x/FluidTransitions could be used together with latest RNRF beta.40

**Comment by caiorios** [comment]
Hey @aksonov , I've been trying to integrate RNRF with FluidTransitions with no success. Could you provide a example?

**Comment by mregan59** [comment]
@caiorios were you able to implement Fluid transitions with RNRF? I found https://github.com/IjzerenHein/react-native-magic-move that works with RNRF but React Navigation's Fluid Transitions has a lot more functionality that I'd like to have access to

**Comment by caiorios** [comment]
> Have you success to use FluidTransitions with RNRF?

It's been a while since I wrote my comment. Nowadays I use [react-navigation](https://github.com/react-navigation/react-navigation) for this kind of thing. I believe that v5 covered all the gaps that make people use RNRF.

For animate the transitions, I believe the best choice is [react-navigation-shared-element](https://github.com/IjzerenHein/react-navigation-shared-element). Unfortunatly it doesn't support version 5 of react-navigation yet.

**Comment by Jojr** [comment]
@caiorios thank you so much.

**Comment by roots-ai** [comment]
How to use `react-navigation-shared-element` with RNRF?
