### ISSUE TITLE
Custom styling of Back Button

### ISSUE THREAD

**Issue by ramneekhanda** [aksonov/react-native-router-flux#286]
I have tried almost everything but i cant do something simple - Change style of default "< Back" text.

I have tried leftButtonTextStyle, backButtonTextStyle and everything possibly other than that. i screened the code as well but saw that no property was being used to render this text (defaults are being applied from ExNavigator and Navigator).

Please confirm what shall i do for this?

Note that i can render everything myself using renderLeftButton.. But i think its just an overkill.

**Comment by ksarna** [comment]
I Have exactly the same issue.

**Comment by plrthink** [comment]
Same issue here. After searching through the code, I find line (https://github.com/aksonov/react-native-router-flux/blob/8b9bd122974785dc8e37ac1d4c9925b3bb2dd9e3/ExRouter.js#L102), so if we don't provide `onLeft` and `leftTitle` this two props to `route` component,  it wouldn't apply the custom styles to the left button text. I don't think this make sense since we only want alter some styles.

**Comment by plrthink** [comment]
Just open a PR to try to solve this issue.
