### ISSUE TITLE
Can't reset and pass props to children scenes under Tab nav

### ISSUE THREAD

**Issue by simonso3** [aksonov/react-native-router-flux#2935]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27 (v3 is not supported)
- react-native v0.52.2

### Expected behaviour
```
...
<Stack key="root">
  <LoginScreen initial/>
  <Tab>
    <Stack>
      <HomeScreen/>
       ...
    </Stack>
     ...
  </Tab>
</Stack>
...
```
Above is the simplified version of my scenes.
Start at the LoginScreen, here is my goal:

#### 2) RESET the stack so the user can't go back to the Login screen once the user landed on HomeScreen

So I tried doing:

**Attempt 1)** `Actions.reset('HomeScreen', params);`

I expected: 
 - No error
 - the stack being reset so users can't go back to LoginScreen
 - HomeScreen is loaded with the params

**Attempt 2)** `Actions.HomeScreen(params);`

 - this doesn't give me any error and HomeScreen is loaded with the params but it doesn't reset the stack so users can still go back to Loading screen onBack (e.g. hardwareBack on Android)

**Attempt 3)** `Actions.reset('Tab', params);`

I expected:
 - the stack being reset so users can't go back to LoginScreen
 - Though props are being passed to `Tab` but I expect/want a way to pass the props down to the children scenes under `Tab`.

### Actual behaviour
1) This gave me and error as `There is no route defined and it can only be ....`
2) This is actually doing what I expected, however I just want to find a way to reset the stack in the same time
3) Params are not being passed down to the children scenes under Tab

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Do the same setup as above
2. Perform attempt 1,2,3 stated above

**Comment by asciifaceman** [comment]
Out of curiosity, could you try wrapping your "authenticated" views in a parent scene and add this panHandlers?

`<Scene panHandlers={null}>`

The way I've begun handling this personally is to use a `Launch.js` that loads first. This view simply checks to see if the app is already logged in, if it isn't, then it goes to LoginView. If it IS then it continues to the authenticated view.

After a login, I pop the user back to Launch.js which rechecks and then shunts to the authenticated view.

This is helpful because even if the user somehow manages to "go back to the beginning" it just rechecks auth and sends them back to their view. LoginView is ONLY accessible if you are not authenticated.

<img width="458" alt="screen shot 2018-03-13 at 10 49 54 am" src="https://user-images.githubusercontent.com/1619591/37359999-482cc5b8-26ac-11e8-840b-1ec2d3aa06ba.png">


hope this helps

**Comment by simonso-nzme** [comment]
@asciifaceman Thanks for the reply! I was using LoginScreen to simplified my example, is actually a loading screen that initialise the app. The approach you mentioned is a good solution, though I would prefer having the RESET functionality to work properly so I don't have to worry about it once the user got to HomeScreen. I've been looking around but it seems that the bug still exists in  RESET and I haven't found a way to pass props from `Tabs` to its children `Scenes`. :(

**Comment by amarkovits** [comment]
I also have this problem. Cant reset/replace to a tabs scene because the props are not passed to the children

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

To 'reset' stack you can use `type='replace'` for your `Tab`, so user cannot go back.
