### ISSUE TITLE
Container offsets

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#316]
Hi, I'm having trouble with my layout. Every time I push a view, I need to have a marginTop attribute so it won't get blocked by the navbar. Is there anyway to solve this issue?

**Comment by aksonov** [comment]
It is not issue but feature and standard behaviour of built-in React Native Navigator (as well as native iOS navigator).

**Comment by ajoshdee** [comment]
In native iOS you can just push a view controller but the view won't be covered up by the nav bar

**Comment by aksonov** [comment]
It is not true. It will be not covered only if you set translucent property:
http://stackoverflow.com/questions/18953509/how-to-prevent-uinavigationbar-from-covering-top-of-view-in-ios-7

Ok, anyway React native doesn't have 'translucent', so you have to set padding. Otherwise transparent nav bars are not possible.
