### ISSUE TITLE
Check the render method of `SceneView` error when upgraded to v4.0.1

### ISSUE THREAD

**Issue by danferd** [aksonov/react-native-router-flux#3171]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.1
- react-native v0.51.1

Getting the below error when upgraded from v4.0.0-beta.31 to v4.0.1
**Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `SceneView`.**

**Comment by fcabrera23** [comment]
Hi, I’m having the some problem! Will try to downgrade flux to see if it’s fixed

**Comment by alejandroclvi** [comment]
Hi, I'm having the same problem, and I'm using react native v0.50.3, any ideas of why?

**Comment by daviscabral** [comment]
I will see if I can reproduce it here and then get back to you guys.

**Comment by daviscabral** [comment]
@alejandroclvi @danferd @fcabrera23 I was not able to reproduce it with the Example that I have here. But I do believe that is because `babel` is misconfigured. What is the `react` and `react-native` versions that you are using?

Could you check if your version is compatible?

| `react-native` | `react`         |
|----------------|-----------------
| 0.46.x         | 16.0.0-alpha.12 |
| 0.47.x         | 16.0.0-alpha.12 |
| 0.48.x         | 16.0.0-alpha.12 |
| 0.49.x         | 16.0.0-beta.5   |
| 0.50.x         | 16.0.0          |
| 0.51.x         | 16.0.0          |
| 0.52.x         | 16.2.0          |
| 0.54.x         | 16.3.0-alpha.1  |
| 0.55.x         | 16.3.1          |
| 0.56.x         | 16.4.1          | 

Also, check this document about what have changed and breaking changes that might help you identify what is going on there.

https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md

**Comment by danferd** [comment]
i'm using:

"react": "^16.4.2",
"react-native": "^0.51.1",

**Comment by daviscabral** [comment]
@danferd but what is the version installed? Try to run these commands to check the versions you are using and if they are compatible.

```shell
$ npm ls react-native
react-native-router-flux@4.0.2-dev /Users/daviscabral/Projects/open-source/react-native-router-flux
└── react-native@0.56.0

$ npm ls react
react-native-router-flux@4.0.2-dev /Users/daviscabral/Projects/open-source/react-native-router-flux
└── react@16.4.1
```

**Comment by aksonov** [comment]
@danferd I can't reproduce it. Make sure you removed node_modules before RNRF upgrade. It is very possible to latest react navigation may not support old react native version. Try to upgrade to latest 0.56.0 or 0.55.4 (I'm using 0.55.4). Check Example project as well. 
Try to simplify your Router to one Scene and check. After that add more scenes one by one.
