### ISSUE TITLE
node_modules_reactnativerouterflux_node_modules_reactnavigationstack_dist_views_assets_backiconmask.png: error: Invalid filename.  Unable to add.

### ISSUE THREAD

**Issue by js1121302139** [aksonov/react-native-router-flux#3264]
"react": "16.4.0",
    "react-native": "0.55.4",
    "react-native-router-flux": "^4.0.1",

android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativerouterflux_node_modules_reactnavigationstack_dist_views_assets_backiconmask.png: error: Invalid filename.  Unable to add.

**Comment by js1121302139** [comment]
Solution: 
node_modules->react-native-router-flux->node_modules->react-navigation-stack->dist->views->assets->backiconmask.png find backiconmask.png delete， to  node_modules->react-native-router-flux->node_modules->react-navigation-stack->dist->views->assets->Header->Header.js change line 334 <Image source={require('../assets/back-icon.png')} style={styles.iconMask} />

**Comment by daviscabral** [comment]
Hi @js1121302139 - glad you found a workaround to this issue. Even happier that you not just found it and come back and wrote it down here and in other issue where other user was having the same problem.

This was a known issue with `react-native` and `gradle` and it seems that is fixed with `react-native@0.57` as seen here: https://github.com/facebook/react-native/issues/16906.
