### ISSUE TITLE
replace not working correctly

### ISSUE THREAD

**Issue by bang9** [aksonov/react-native-router-flux#3529]
### Version
- react-native-router-flux v4.0.6
- react v16.8.3
- react-native v0.59.3

### Expected behaviour
initial screen stack : [A]
1. Push B : [A,B]
2. Replace C : [A,C]
3. Push B : [A,C,B]
4. Replace C : [A,C,C] or [A,C]

### Actual behaviour
initial screen stack : [A]
1. Push B : [A,B]
2. Replace C : [A,C]
3. Push B : [A,C,B]
4. Replace C : [C]

This error occur when I replace screen that already exist in the navigation stack. (Pop all screen)

**Comment by KaoPengHsiang** [comment]
I have same issue! Have you found the way to fix it ? ><"

**Comment by filmhomage** [comment]
Same issue here. Any update?

**Comment by AlekseyKutsko** [comment]
Hi! I faced with same issue. Are there any updates?

**Comment by AlekseyKutsko** [comment]
I found where the problem. 
`⁨node_modules⁩ > ⁨@react-navigation⁩ > ⁨core⁩ > ⁨lib⁩ > ⁨module⁩ > ⁨routers⁩ > StackRouter.js`. 
StackRouter has getStateForAction method(line 133)  in which determinate lastRouteIndex variable(line 173). If lastRouteIndex equals -1, it creates new route(line 204). But in our case lastRouteIndex doesn't equal -1, because `r.routeName === action.routeName`. It found previous route with same routeName. 

```
              var lastRouteIndex = state.routes.findIndex(function (r) {
                    if (action.key) {
                        return r.key === action.key;
                    } else {
                        return r.routeName === action.routeName;
                    }
                });
```
I didn't find how to pass `action.key`.

I pass unique id in each replace method, to create new route with this id(line 204).
Creating new route:

```
           _route = {
                  params: getParamsForRouteAndAction(action.routeName, action),
                  routeName: action.routeName,
                  key: action.key || generateKey(),
                  sceneId // my unique id
            };
```

I added next condition in logic of the lastRouteIndex:

```
              var lastRouteIndex = state.routes.findIndex(function (r) {
                    if (action.key) {
                        return r.key === action.key;
                    } else if (r.routeName === action.routeName && sceneId) { // my condition
                        return r.sceneId === sceneId;
                    } else {
                        return r.routeName === action.routeName;
                    }
                });
```

Checking ids solved the problem. 

This id need to pass through 1) interface ActionsGenericStatic in index.d.ts,  method replace in navigationStore.js, Reducer.js(**react-native-router-flux**); 2) method getStateForAction in SwitchRouter.js, StackRouter.js(**@react-navigation**); 3) method getStateForAction in  DrawerRouter.js(**react-navigation-drawer**).

I hope this help you.
