### ISSUE TITLE
Key login is already defined - HMR 0.22

### ISSUE THREAD

**Issue by PeterKow** [aksonov/react-native-router-flux#376]
I am on `react-native 0.22` and `react-native-router-flux 3.1.3` with hot reloding [HMR], after first HMR reload I got following error 

![image](https://cloud.githubusercontent.com/assets/10186048/13956908/730928a0-f042-11e5-8c2a-988066f2b0f9.png)

Problem is caused by `Actions.create`

This is my current setup:
```javascript
let scenes = Actions.create(
     <Scene key="root">
            <Scene key="login" component={Login} title="Login"/>
          </Scene>
);

 <Provider store={store}>
      {() =>
        <Router scenes={scenes} />
      }
    </Provider>
```

I tired this also, but doesn't work at all - nothing renders
```javascript
 <Provider store={store}>
      {() =>
        <Router>
          <Scene key="root">
            <Scene key="login" component={Login} title="Login"/>
          </Scene>
        </Router>
      }
    </Provider>
```

Temporary solution is to call when working with HMR is to call components directly without Router

```javascript
{() =>
        <Login/>
      }
..

Let me know if you have any ideas, so I can test them :)

**Comment by aksonov** [comment]
Check latest version

**Comment by zxcpoiu** [comment]
same issue using 3.1.5

**Comment by aksonov** [comment]
It is not true. 3.1.5 doesn't throw exception for existing keys anymore
```
 if (this[key]){
            console.log("Key " + root.key + " is already defined!");
        }
```

**Comment by zxcpoiu** [comment]
oh sorry, I mean, I didn't got a red screen but same issue which is "key xxx is already defined."

**Comment by aksonov** [comment]
It is not issue but logging. It still could be usable if user really defines several scenes with the same key. For hot reload you could ignore it.

**Comment by zxcpoiu** [comment]
@PeterKow

I think it is caused by wrap `<Router>` into `<Provider>` and maybe it is redux triggers `<Router>` to re-render.
you can try Example and print some log in `render()` and `onComponentDidMount`, you will find that `<Router>` only render at the initial stage.

is your `<Router>` render several times also?
I'm still trying to find a better way to wrap `<Provider>`

**Comment by PeterKow** [comment]
Works after updating to 3.1.5

@zxcpoiu I tried without Provider and that wasn't a problem

Thanks!

**Comment by agrass** [comment]
I'm still having this issue. Any idea how to solve it? I have the camera in one scene and is rendering multiples times and finally the app crash due low memory

**Comment by mmazzarolo** [comment]
@zxcpoiu is right, re-rendering <Router /> (for example by wrapping it in a Provider) prints that log.

**Comment by jsdario** [comment]
How can we not wrap it into a provider? Any examples we could follow? I am stuck here and it was the recommended implementation on the docs https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md

**Comment by zxcpoiu** [comment]
by my suffering experiences, there is no way to prevent `Router` re-render if you wrap it under a `Provider` and listen updates from `redux`, it is a nature by design.

the point how to prevent this, is: **`Router` should render once and just once**
it means:

If you didn't connect to redux at all, it works fine since your `Router` would not be triggered by any of updates from redux.

Also, you can `connect()` `Router` to `redux` to get a `dispatch()` method props but you can NOT listen to another props.

Thus, the architecture would be:

```jsx
import {
    Router,
    Scene,
    Actions,
} from 'react-native-router-flux';


// --- child component can connect and listen to props they want.
const myConnectedMainConponent = connect()(myMainConponent);
const myConnectedLoginConponent = connect()(myLoginConponent);

// --- Create it via Actions.create(), or it will be re-created for each render of your Router
const scenes = Actions.create(
    <Scene key="root">
        <Scene key="login" component={myLoginConponent} />
        <Scene key="main" component={myMainConponent} />
    </Scene>
);

// --- Create connected Router if you want dispatch() method.
// --- Or you can just use vanilla Router
const myConnectedRouter = connect()(Router);

// --- your exported main router
export default class MyExportedRouter extends React.Component {
    constructor(props) {
        super(props);
    };

    render() {
        return (
            <Provider store={store}>
                <myConnectedRouter scenes={scenes} />
            </Provider>
        );
    }
}
```
p.s. I typed above codes directly here, be aware the syntax error :)


**Point Taken:**

1. `Router` should render once and just once ( connect to get dispatch method only or not connect at all )
2. pre create scenes via Actions.create() and pass it into Router
3. move your app main logic into one of the children of Router

**Comment by zxcpoiu** [comment]
put it in doc #1098

**Comment by jsdario** [comment]
Hi. Thanks @zxcpoiu for the hints, I made some progress. This [question I posted in stackoverflow](http://stackoverflow.com/questions/39098032/how-to-properly-use-redux-with-react-native) is becoming sort of popular. You may want to answer as you answer this one so I can credit you for your help.

**Comment by zxcpoiu** [comment]
@jsdario thanks! glad it helps! :smile:

**Comment by lucasff** [comment]
@zxcpoiu hey, the wording is not so great, we are trying to use your approach even we have the same problems with the latest version of RN/RNRF

**Comment by zxcpoiu** [comment]
@lucasff 

I didn't upgrade my libraries for a while neither `react-native-router-flux` nor `redux`, so I'm not sure if it changes.

I think the most important thing you might want to solve first is to **make sure your router render once and only once**

you can `console.log("XXX")` in your router's `render()` function, then try to do anything you need to do until "XXX" only shows once.

there is so many factors may cause router to re-render, and the most difficult part is to redesign your app's architecture.
