### ISSUE TITLE
router bar crash and no show title

### ISSUE THREAD

**Issue by DThink** [aksonov/react-native-router-flux#404]
hi, the react-native-router-flux is very helpful easy plugin. thanks for this. unfortunately encountered some problems, I do not know if because of me or because of a malfunction of the plugin. the problem is this
1)in the router bar if i see a title, this is to bottom of bar and the bar is too big respect you example.
  
![router-1](https://cloud.githubusercontent.com/assets/18085313/14059853/874c513c-f350-11e5-96d4-1741ff45d706.png)

2) if i go to next page in the router bar i dont see the title and if i push the back button the app crashes
   
![router-2](https://cloud.githubusercontent.com/assets/18085313/14059860/cf14404c-f350-11e5-8ce0-8256a24d04de.png)

i install the last react native version in windows 10, i tested the app in the genymotion emulator with android 6.0, 5.1 and 4.4 but in same case the problems is the sames.
how do I fix this? for me it is important to consider this plugin one of the best.

**Comment by aksonov** [comment]
Kind of duplication #355. Sorry, ask React Native team to support ExperimentalNavigation properly for Android/Windows! This component is just wrapper around it.

**Comment by DThink** [comment]
how do I contact their team?

**Comment by rulatir** [comment]
Weirdly enough, this doesn't seem to even be caused by navigating. Basically [any component updating inside a scene](https://github.com/facebook/react-native/issues/6666#issuecomment-201891922) results in memory being leaked and **exponentially so**, except when the scene is the very root scene - the problem does not show in that case.
