### ISSUE TITLE
Possibility to turn of gestures

### ISSUE THREAD

**Issue by mckn** [aksonov/react-native-router-flux#619]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.22.23
- react-native v0.22.2

### Expected behaviour

- Be able to define if a Scene should use gestures or not.
- If gestures is turned off you should not be able to swipe away the Scene

**Comment by aksonov** [comment]
Have you tried panHandlers={null} ?

**Comment by mckn** [comment]
Yes, I have tried it but without any success :/

**Comment by aksonov** [comment]
Sorry, i can't reproduce, maybe you don't use RN0.22

**Comment by alex88** [comment]
Same here, RN0.26 

```
      <Router>
        <Scene key="root">
          <Scene key="home" component={Login} hideNavBar={true} initial={true}/>
          <Scene key="timeline" direction="vertical" panHandlers={null} component={Timeline} />
        </Scene>
      </Router>
```

and still on the second scene I can swipe to go back

**Comment by alex88** [comment]
With RN0.26 same thing, my code is:

        <Scene key="root">
          <Scene key="home" component={Login} hideNavBar={true} initial={true}/>
          <Scene key="timeline" panHandlers={null} direction="vertical" component={Timeline} />
        </Scene>

and I'm still able to swipe down to go to the previous view

**Comment by markgoodyear** [comment]
I believe I have the same/similar issue. Here is a description of what I have:

```
<Scene key="root" hideNavBar={true} hideTabBar={true}>
  <Scene key="Main" component={Main} title="Main Scene" initial={true} />
  <Scene key="Settings" direction="vertical">
    <Scene key="SettingsOne" component={SettingsOne} title="Settings One" />
    <Scene key="SettingsTwo" component={SettingsTwo} title="Settings Two" panHandlers={null} />
  </Scene>
</Scene>
```

I can swipe down on `SettingsOne` to pop back to the `Main` scene. If I navigate to `SettingsTwo` from `SettingsOne` I can still swipe down to pop back to the `Main` scene despite `panHandlers={null}` being set. Setting `panHandlers={null}` just prevents a horizontal gesture, but not the vertical one. When swiping down on `SettingsTwo`, it reveals the content of `Main`, but then will pop back to `SettingsOne`, and it'll slide up, which looks odd. Here is a gif of it to explain a little better: http://d.pr/i/grX1/1K3ywzTr.

Of course, this could be intentional behaviour, but setting `panHandlers={null}` on `SettingsTwo` I would assume that scene would have no gestures at all.

**Comment by davidbiller** [comment]
panHandlers={null} dosent work on RN 0.26.3
