### ISSUE TITLE
Re-implement hidden tabs from tabbar behavior

### ISSUE THREAD

**Issue by Elyx0** [aksonov/react-native-router-flux#736]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.2
- react-native v0.26.2

In the previous versions not supplying ` icon={TabIcon}` to a Scene inside a `tabs={true}` component allowed to hide the tab from the tabbar, but still be allowed to navigate to it using `Actions`. 
After upgrading from `"react-native-router-flux": "^3.2.7",` to latest, this behavior is gone.

### Steps to reproduce

```javascript
    <Scene key="tabbar" hideNavBar={true}  tabBarStyle={tabBarStyle.bar}  tabs={true} default="me">
        <Scene key="1" icon={TabIcon} title="1">
          <Scene key="1_1" component={1_1}  title="Browse"/>
        </Scene>
        <Scene key="2" icon={TabIcon} title="2">
          <Scene key="2_1" component={2_1} />
          <Scene key="2_2" component={2_2} />
       </Scene>
        <Scene key="magicHiddenTab" /* icon={TabIcon} */  hideTabBar={true} >
        </Scene>
        <Scene key="3" component={3} icon={TabIcon}  />
        <Scene key="4" component={4} icon={TabIcon}  />
      </Scene>
```

**Comment by aksonov** [comment]
agree, @joenoon could you fix that?

**Comment by ms88privat** [comment]
the old behaviour sounds like a bug to me. But I can see the usefulness of it. Can we make it by explicit setting a new prop like `hideTab={true}` ?

**Comment by joenoon** [comment]
agree it seems like more of a bug than a feature - but maybe there is a valid use case there that I just dont use.  I have a branch in progress that brings back the old tab implementation exactly as it was, and fixes the part I couldnt get working before for the scene rendering.  so hopefully all of these problems since the new tab implementation will go away soon.

**Comment by Cordazar** [comment]
One use case is where you want a small amount of tabs (main functionality/views of the app) to be shown on most of the scenes.

**Comment by rturk** [comment]
Hi @Elyx0 Can you elaborate why you need this? Looks like that your `magicHiddenTab` can easily be placed as a sibling to `tabbar` and by default it will be hidden if you use switch. Or for a more sophisticated design you'll be able to hide it using redux. 

I agree with @ms88privat this old behaviour is more like a bug that could lead to incongruent scenarios where it will be hard to define what shows or not a tab.

**Comment by rturk** [comment]
@Cordazar what you're describing can't be achieved with nested scenes?

**Comment by Cordazar** [comment]
@rturk I can't see how.

10 Views numbered 1-10.
View 1 and 2 should be in the tab bar for Views 1-8 but not on View 9-10. 
How would you nest that?

**Comment by mat2maa** [comment]
I'm wondering how this plays with the inclusion of a Drawer. In the [documentation for a Drawer](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#drawer-side-menu-integration), it is suggested that within the "drawer" Scene you include a scene with `tabs={true}`, presumably so that children scenes will automatically set `type='jump'`.

However, doing so leads to something like [the referenced issue](https://github.com/aksonov/react-native-router-flux/issues/725):

> Error: Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `TabNavigator`.

Is the `tabs={true}` therefore erroneous in the documentation OR is this example a reason that the above is a feature rather than a bug?

**Comment by rgovindji** [comment]
I am having trouble with the tab bar as well, maybe it's related to this. I want to display the tab bar for scenes that I have declared outside of the tab bar scene but have navigated to from a scene within a tabbar. Is that possible?

**Comment by joenoon** [comment]
@rgovindji that sounds to me like you want this:

You click a tab, click a user's name which should open their profile.  That could happen from any tab at any depth.  The expected behavior would be to "push" the profile screen into the current navigation flow (current nav/tab).  And then when browsing that profile, you might see a "friends" section and find someone else to click... their profile would then be pushed as well.  You would get back to the root of the tab my going Back, Back on the nav bar.

If that sounds like the flow you want, thats exactly what the "clone" feature allows.  You can check the Example app where its used in the tabbar demo:  EchoView, push new scene, all of the inherit/explicit options for hideNavBar/hideTabBar etc.

**Comment by rgovindji** [comment]
@joenoon thanks a lot that is exactly what I was looking for 👍
