### ISSUE TITLE
onEnter

### ISSUE THREAD

**Issue by skeie** [aksonov/react-native-router-flux#78]
Hi, 

In the example below, the onEnter works for `Route` with the name `routeDetail`, but now fot the `Route` with name `home`

```javascript
<Router hideNavBar>
                <Route  onEnter={(route)=>{console.log(route.getName()); return true;}} name="routeDetail" component={RouteDetail} {...props} schema="withoutAnimation" />
                <Route name="map" component={Map} {...props} schema="default" />
                 .......
                <Route name="tabbar" initial>
                    <Router footer={TabBar} style={{backgroundColor: vars.navColor}} hideNavBar>
                        <Route onEnter={(route)=>{console.log(route.getName()); return true;}} name="home" schema="tab" component={Home} {...props} imageSource={require('image!home')} />
                  ......
                </Route>
            </Router>
```

Is it possible to fix it?

**Comment by chetstone** [comment]
You have a route as a child of a route? I think you need to wrap it with a router:
```
<Route name="tabbar" initial>
      <Router footer={TabBar} showNavigationBar={false}>
                        <Route onEnter={(route)=>{console.log(route.getName()); return true;}} name="home" schema="tab" component={Home} {...props} imageSource={require('image!home')} />
```

Don't know if that will fix your problem or not, but what you have doesn't look right.

**Comment by skeie** [comment]
Sorry, we have a Route then a Router then a Route. I updated the example now.

**Comment by aksonov** [comment]
2.x version doesn't have onEnter and i'm thinking is it necessary to have? Why onPop/onPush/onReplace is not enough?

**Comment by lynndylanhurley** [comment]
@aksonov - `onEnter` is useful to me because most of the time it doesn't matter if a screen is visited using `onPop`, `onPush`, or `onReplace`. One example is authentication:

~~~js
// checks if user is signed in, otherwise redirects to login.
function isSignedIn() {
  if (store.getState().signedIn) {
    Actions.Login();
  } else {
    return true;
  }
}

// ...

<Router>
  // non-authenticated users can only see these routes
  <Router name="Auth">
    <Route name="LogIn" initial={true} component={LogIn} />
    <Route name="SignUp" component={SignUp} />
  </Router>

  // authenticated users can see these routes
  <Router name="Account" onEnter={signedIn}>
    <Route name="Dashboard" component={Dashboard} initial={true} />
    <Route name="Messages" component={Messages} />
</Router>
~~~

In order to accomplish this with `onPop`, etc. I would need to add the `isSignedIn` method to the `onPop`, `onPush`, and `onReplace` handlers of each individual route. I would rather have a single `onEnter` handler that operates at the `Router` level.

**Comment by JonasJonny** [comment]
+1

**Comment by aksonov** [comment]
PR would be welcome! You need to add this functionality into ExRouter

**Comment by aksonov** [comment]
3.0 is released. Closing it for now, because it is for outdated version (2.x)

**Comment by diegorodriguesvieira** [comment]
how can I get onEnter on 3.x?
