### ISSUE TITLE
Go back to any scene before current one?

### ISSUE THREAD

**Issue by Swordsman-Inaction** [aksonov/react-native-router-flux#804]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.16
- react-native v0.26.3

### Expected behaviour
Let's say we have a scenes stack like this: A -> B -> C -> D -> E
I'm at E scene now, and I want to go back to B, I need the stack to be A -> B.
The action is that we go back to B, and clear C, D, E. A and B won't be refreshing again.

### Question:
Is there a way to do this kind of action? I don't want to use pop() to achieve this, since I may need to pop many times. `Actions.B({type: 'reset'})` is great except it will make B become the root scene and also refresh B

If there is no better way to do this, can you add a nice feature in the future?
Like: add a new type named `clear`, then we can use `Actions.B({type: 'clear'})` to do this.

PS: Sorry for my poor English.

**Comment by nitsujri** [comment]
@Swordsman-Inaction for us, we ran into this with confirmation modals. 

`Bookings Index => Booking page => Confirm booking Modal => Booking confirmed Modal`

We wanted to go back to `Booking page`. Our solution was to double `pop()`.

A `clear` would be nice, but not necessary since you can maintain the stack size through the store. Given the amount of effort required just to keep up to date with RN, it's best if you coded your need and made a PR. We had to do that for `reset`.

Hope I'm not coming off as mean, just the reality of the situation.

**Comment by aksonov** [comment]
#798 could help here?

**Comment by Swordsman-Inaction** [comment]
@aksonov @nitsujri @rseemann you guys are awesome

**Comment by rseemann** [comment]
@Swordsman-Inaction I still haven't had time to work further on this, but if you need this ASAP and your tree structure is simple enough you could try the fork for now.

**Comment by Swordsman-Inaction** [comment]
@rseemann I'll try it, thanks
