### ISSUE TITLE
[WIP] Migrate to newest React Native master branch API (0.29?)

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#815]
All, hopefully @joenoon ,i've started 0.29-WIP branch where trying to use latest ExperimentalNavigation API. Internal structure was changed (route/routes keys instead of children, etc.), RootContainer was removed, onNavigate was removed and so on. A lot of breaking changes :(

I've made some significant progress and successfully run demo (i.e. without compile errors :), but there is a lot to do:
1. NavBar support (now just null returned)
2. TabBar support
3. Custom renderer support (i.e. modal) Looks like we can't use NavigationCardStack for that within DefaultRenderer
4. Replace action
5. Drawer support - we will not use context but changing state instead.
6. ESLint errors

I have limited time to work on it (spent almost whole day on it already) but I believe everybody would be interesting in this release, because it will finally allow to de-couple navigationState from React and move navigation logic into Redux/MobX/other store - just by connecting Router to Redux and pass own navigationState to Router (some breaking changes would be necessary, now it is possible to use both dispatch & internal state update within Router, we probably will do conditional select - redux dispatch OR internal dispatch.

So please write here if you want to assign some task.

**Comment by joenoon** [comment]
@aksonov yes this will be a big and important release for a few reasons.  I'm in a similar situation with time - I don't have much of it - but as my app depends heavily on this navigation I think I can find some time this week.  I'll post back here when I can actually start so we can coordinate better and not repeat work.  BTW I tried your MobX integration and its awesome!

**Comment by aksonov** [comment]
Just found that NavigationAnimatedView is deprecated as well, so we have to remove it. Also we need to rework our 'focus' event to work as described here:
https://github.com/ericvicenti/navigation-rfc/issues/82

**Comment by cridenour** [comment]
Now that our app is out, I should have some time later this week to play around as well. I'll check back in before then to see where there's a need.

**Comment by joenoon** [comment]
I'm in the process of getting my app working again with 0.27 (just about to have it working now) so I'm a ways behind still.

As part of this I started using MobX with wrapBy which is really great ( thanks @aksonov ).

I'm curious to see what will happen as I move past 0.27 to 0.28/0.29 since it sounds like managing the navigationState will now be left to the user.  I'm not sure if that means everyone will need to supply their own store interface outright, or there will need to be a store-interface for the common ones (mobx-rnrf-store, redux-rnrf-store, etc).

Anyway, just wanted to give a little update and hopefully I'll have some time over the next few days to explore the path forward.

**Comment by aksonov** [comment]
@joenoon Any news? About managing navigationState - i believe we could support both ways - if navigationState is passed as prop then no internal state management, otherwise - use this.state.navigationState and change it accordingly.

**Comment by aksonov** [comment]
cc @cridenour

**Comment by joenoon** [comment]
@aksonov I'm still on 0.27 here and about to try moving to 0.28 or 0.29 soon.  Looking at the RN release notes it still looks like tons of stuff is changing in NavigationExperimental.  Since rnrf is not tied to the NavigationExperimental upstream I'm finding for my app rnrf works fine as is for now.  So I'm not really in a hurry to try and update the NavigationExperimental dep until its more stable, or there would be some real benefit at the app level.

**Comment by aksonov** [comment]
Agree, let's wait until no changes within NE API atleast during 7-10 days :)

**Comment by cridenour** [comment]
We haven't had any issues with 0.27, but we haven't gone into full QA mode. Now that we package NE with RNRF, it seems RN's 2 week release cycle should be less hectic now!

**Comment by joenoon** [comment]
BTW great decision to package NavigationExperimental with RNRF.  I thought it was going to create lots of problems but it turned out to solve most of the problems.  So to everyone who pushed for that 👍

**Comment by boorad** [comment]
Do you guys think that a problem I'm having with RNRF 0.32.0 and RN 0.29.2 (yes, I'm trying it out) could lead to a TimerMixin error during a transition?

    Unhandled JS Exception: _clearer is not a function. (In '_clearer(id)', '_clearer' is undefined)

And here's the stack I get:

![screen shot 2016-07-27 at 3 56 32 pm](https://cloud.githubusercontent.com/assets/15431/17190151/cce1a936-5412-11e6-8ac1-b20ff950bb75.png)

I'm curious if this is relevant to this thread about getting on a more modern RN, and if I'm crazy for even trying 0.29 right now.  Also, I can't find the 0.29-WIP branch that @aksonov mentioned in the OP.
