### ISSUE TITLE
leftButtonImage does not render

### ISSUE THREAD

**Issue by rowellx68** [aksonov/react-native-router-flux#837]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.0
- react-native v0.27.2

### Expected behaviour
NavBar should render the `leftButtonImage` if it is provided.

### Actual behaviour
`leftButtonImage` is not rendered

### Steps to reproduce

1. Create a scene that has a `leftButtonImage`

**Comment by bestofsong** [comment]
+1

I could use 

```
renderBackButton={()=>{return null;}} renderLeftButton={bla~bla~bla} onLeft={bla~bla}
```

to render a left button, but I then must put onLeft function into my render function for it to work.

By the way, I think is better for onLeft to be  implemented each visible scene, because maybe a scene have to interact with user before calling Actions.pop()?

Also, in iOS, if a left button is provided for the navigation bar, the back button is not rendered then, but here things are reversed(<https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md>), maybe this is related to the op's issue?

**Comment by rowellx68** [comment]
The idea was to render the `leftButtonImage` when we are presented with the initial Scene. With the modification I did for https://github.com/aksonov/react-native-router-flux/pull/838, I get the results below.

![img_1610](https://cloud.githubusercontent.com/assets/10155704/16176433/40f58d44-3607-11e6-926e-c3f632a219a3.jpg)

Tapping the gear button takes us to another scene. The navbar keep the default behaviour of presenting a back button:

![img_1611](https://cloud.githubusercontent.com/assets/10155704/16176451/b59f1340-3607-11e6-887b-bd524edf0219.jpg)
