### ISSUE TITLE
TabBar may select two tab in Example

### ISSUE THREAD

**Issue by gyson** [aksonov/react-native-router-flux#84]
Version: 1.0.9 with Example

Reproduce: enter navbar view (in "Tab # 1") and then tap "Switch to tab3" button. Now both "Tab # 1" and "Tab # 3" are selected (in red).

Screenshot: ![screen shot 2015-12-17 at 11 41 39 pm](https://cloud.githubusercontent.com/assets/4263515/11889550/70003d94-a518-11e5-8d7d-a396f3deda24.png)

Not sure if this is a bug in Example, react-native-router-flux or react-native-tabs at the moment.

**Comment by vanBrunneren** [comment]
:+1:

**Comment by iZaL** [comment]
confirmed

**Comment by MITDelian** [comment]
Thanks for the report! I'll take a look

**Comment by MITDelian** [comment]
Ok @aksonov I found the issue. In `react-native-tabs` you maintain a selected element in the state. However I think if a selected prop is passed in, then that should override the component state. The issue is in this line:

https://github.com/aksonov/react-native-tabs/blob/master/index.js#L60

Basically `self.state.selected` is still `"tab1"` and so it's cloning the element where the prop of selected is still true. My proposition is to make it so that the line is 

`{!self.props.selected && (self.state.selected == el.props.name) ? React.cloneElement(el, self.state.props) : el}`

instead of what it currently is which is:

`{self.state.selected == el.props.name ? React.cloneElement(el, self.state.props) : el}`

Will be submitting a PR shortly and will make sure this doesn't cause any other breaking changes

**Comment by MITDelian** [comment]
Here is the submitted PR: https://github.com/aksonov/react-native-tabs/pull/9

**Comment by aksonov** [comment]
Should be fixed with latest 2.0 version, please check

**Comment by gyson** [comment]
Just checked with v2.0.4 and it's fixed now :)

Great work! @MITDelian , @aksonov
