### ISSUE TITLE
How can I trigger 'onRight' in scene and update its componet's state

### ISSUE THREAD

**Issue by jingpeng** [aksonov/react-native-router-flux#979]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.26.13
- react-native v0.26.3

**Comment by jingpeng** [comment]
I want to use default wrapped navbar in tag <Scene/>, but I find the onRight function cannot update component's state with Actions.refresh(<PARAMS>). Besides, I don't want use event/subscribe mechanism, so how can I update component's state?

**Comment by cridenour** [comment]
It won't be able to. You should move the state above the component as the NavBar cannot access another component's state. 

If you want to use refresh, you can access it via `this.props` but I highly suggest a Flux implementation.

**Comment by jingpeng** [comment]
Yes, it seems we can only use refresh to update the props and use componentWillReceiveProps to update state

**Comment by aksonov** [comment]
@jingpeng Maybe I've misunderstood something, but why you can't call refresh from onRight?

**Comment by aksonov** [comment]
Oh, got it, you are talking about internal state of component... But for most cases you may use navigationState instead of component's state with RNRF...

**Comment by jingpeng** [comment]
Because I met a case that when clicking right button in NavBar, the internal component need to pop up a modal dialog, so I need to use 'refresh' method and thanks for your explanation

**Comment by sorenburon** [comment]
@aksonov What do you mean by "But for most cases you may use navigationState instead of component's state with RNRF", and how does it solve @jingpeng challenge?

Right now I'm using redux for my app state, and when I need to show a dialog when pressing a button in the NavBar I have to update the app state, and then in componentWillReceiveProps check if I should show the dialog or not. Is there any smarter way of doing this, by using navigationState (or any smarter way in general?). Thanks in advance.
